---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 15/10/2018 20:40
---

vRP.prepare("vRP/currency_tables",[[
CREATE TABLE IF NOT EXISTS vrp_srv_currency(
  dkey VARCHAR(100),
  dvalue TEXT,
  last_time_update INTEGER,
  CONSTRAINT pk_srv_data PRIMARY KEY(dkey)
);
]])
vRP.prepare("vRP/set_srvcurrency", "REPLACE INTO vrp_srv_currency(dkey,dvalue,last_time_update) VALUES(@key,@value,@last_time_update)")
vRP.prepare("vRP/get_srvcurrency", "SELECT dvalue FROM vrp_srv_currency WHERE dkey = @key")
vRP.prepare("vRP/get_srvcurrency_time", "SELECT last_time_update FROM vrp_srv_currency WHERE dkey = @key")

