---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 15/10/2018 23:19
---

local currency_mysql = module("modules/General/mysql/currency") -- apenas para iniciar

if currency_mysql then
    if Debug.active then
        Debug.log("Currency Mysql is loaders")
    end
end

-- Start thread async
async(function()
   vRP.execute("vRP/currency_tables")
   vRP.getCurrency()
end)

Citizen.CreateThread(function()
    while true do
        vRP.currencyUpdater()
        Citizen.Wait(600000)
    end
end)

