---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 15/10/2018 20:08
---


function vRP.generateUUID()
    local uuid = module("lib/uuid4")
    return uuid.getUUId()
end

