---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 15/10/2018 20:18
---

local config = module("cfg/general/utils/currency")

vRP.currency = {} -- free Api
vRP.currencySpecial = {} -- fix api config


