---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 15/10/2018 20:19
---


local cfg = {}

cfg.real_life_money = true
cfg.currency_especial = false ---BTC,XAU,AUG -- if this is true u need to provide a fixerApiKey
cfg.currencyReset = 12*60
cfg.currencyEspecialReset = 24*60
cfg.fixerApikey = "" ---You can find a api key in this site https://fixer.io

return cfg
